### ISSUE TITLE
ROS2 humble supportability

### ISSUE THREAD

**Issue by TZECHIN6** [GPrathap/autonomous_mobile_robots#7]
Hi, I want to use this education material for practice, does it competiable with ROS2 humble in Ubuntu 22.04 (jammy)? Great thanks

**Comment by GPrathap** [comment]
Hi there, it does.

Enjoy!

**Comment by TZECHIN6** [comment]
![Screenshot from 2023-10-25 17-35-14](https://github.com/GPrathap/autonomous_mobile_robots/assets/66129247/1a10e5e1-7fe5-4084-98e6-8b27352b0c43)

### Steps
1. create workspace/src
2. git clone inside src
3. run rosdep and colcon build
4. `ros2 launch hagen_gazebo hagen_car.launch.py`

It freeze after launch... the differential can be launched but not the car model.

**Comment by GPrathap** [comment]
Hi there, 

Just follow the instructions provided here https://github.com/GPrathap/autonomous_mobile_robots/tree/master/hagen 

To launch `ros2 launch hagen_gazebo hagen_car.launch.py` 

You should see something similar to 

![Screenshot 2023-10-25 11:35:05](https://github.com/GPrathap/autonomous_mobile_robots/assets/7587302/708440c4-ed00-4e12-8191-115babab195a)

**Comment by TZECHIN6** [comment]
Yes i follow each step, but I couldnt get to what you have shown in the pictures...

For the Gazebo, what version have you installed? i found there are multiple version of gazebo, gazebo-ros, gazebo11, gz-harmonic

**Comment by GPrathap** [comment]
You need to have gazebo11
